# Generated by Django 2.2.7 on 2019-11-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
