# Generated by Django 2.2.7 on 2019-11-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_auto_20191107_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
