# Generated by Django 2.2.7 on 2019-11-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_auto_20191107_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='goal',
            new_name='quantity',
        ),
    ]
