# Generated by Django 2.2.7 on 2019-11-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_auto_20191108_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='actual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
