# Generated by Django 2.2.7 on 2019-11-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0005_history_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='record',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
